### ISSUE TITLE
Can changing channel be instant(ish) ?

### ISSUE THREAD

**Issue by stuaxo** [StanfordSNR/puffer#13]
This seems pretty responsive, but do you have metrics to test how quickly channels can be changed ?

Is it worth having lower quality versions of the streams that could come up initially while the main channel loads.

I'm thinking about the analogue TV experience, where you can change channel and instantly see something.

**Comment by francisyyan** [comment]
Hi,

Thanks for your question! Yes, we have metrics to test that and we will be posting our paper draft containing performance results on the website in about two days. Please stay tuned!

It would also be great if you could post any follow-ups to our [Google group](https://groups.google.com/forum/#!forum/puffer-stanford) since this is not actually an issue. Thank you!

Best,
Francis
