### ISSUE TITLE
Support wide layout in web frontend

### ISSUE THREAD

**Issue by dveeden** [StanfordSNR/puffer#35]
Currently the layout has the video on the left and a column of channels on the right.
![image](https://user-images.githubusercontent.com/1272980/225559944-dcd9faa5-3f5e-481d-b41c-fc84f06c3b04.png)

I would propose something like this:
![image](https://user-images.githubusercontent.com/1272980/225558522-5d92d248-66ee-4c48-932d-b96cc74fb5b0.png)

This was done with the Firefox developer tools:
- Change the width of `.col-md-9` from 75% to 100%. This is for the video div.
- Change the width of `.col-md-3` from 25% to 100%. This is for the channel list div.
- Change `.list-group` from `flex-direction: column` to `flex-direction: row`.

This allows the video to be slightly larger without having to use the pop-out feature of the browser.

**Comment by francisyyan** [comment]
Sorry I realized that I forgot to reply when going through the open issues. I already took your advice a year ago and increased the video size! I didn't implement it exactly the way you proposed due to other design considerations, but expanding the viewport a bit has probably achieved the same goal.

**Comment by dveeden** [comment]
@francisyyan Thanks. It indeed is a good improvement that achieves the goal.
